### PR TITLE
Properly close connections and implemented client pooling

### LINKED ISSUE #14: No method to close the connect
get := func(path string) (w *httptest.ResponseRecorder, err error) {
		h := php.NewHandler("", "tcp", "127.0.0.1:9000")
		r, err := http.NewRequest("GET", path, nil)
		if err != nil {
			return
		}
		w = httptest.NewRecorder()
		h.ServeHTTP(w, r)

		return
	}

How to close ServeHTTP conn?

### LINKED ISSUE #15: PHP-FPM max_children
If I load the page five times or more, I run out of process managers.

`php_1  | [31-Jan-2018 14:43:10] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`

You can view the [repo](https://github.com/levidurfee/gowafp/tree/5d52d5104701fe3b8ac1231f29db8b725bf8bdf5) if you need to see what I'm doing.

Is gofast closing the FastCGI connections? Reusing them? Any help is appreciated :)

### PR DESCRIPTION
**Pull request by yookoala**
fix #14 (see a305adc).
fix #15 (new ClientFactory interface with ClientPool).

### CODE REVIEW

**Comment by yookoala** [comment]
@levidurfee: Could you please help to test this branch and see if it fixes your issue? Thanks.

**Comment by levidurfee** [comment]
Yes, I would love to test it! Thank you :) I'll give you some feedback tomorrow.

**Comment by yookoala** [comment]
@levidurfee Any luck?

**Comment by levidurfee** [comment]
Sorry, I forgot :)

Just tried it out and it is fixed! Thank you!

**Comment by yookoala** [comment]
@levidurfee No need to sorry.

Thank you very much for testing :-)

**Pull request merged**
